# Generated by Django 6.0.2 on 2026-03-06 03:32

import django.contrib.postgres.indexes
import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_sources', '0003_article_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='article_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='article_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='article_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
