# Generated by Django 6.0.2 on 2026-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_sources', '0004_article_article_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
