# Generated by Codex on 2026-03-08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_sources", "0005_article_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePassage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="news_sources.article",
                    ),
                ),
            ],
            options={
                "ordering": ["article_id", "position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "position"),
                        name="unique_article_passage_position",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="articlepassage",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("text", config="simple"),
                name="article_passage_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="articlepassage",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="art_passage_embed_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="articlepassage",
            index=models.Index(fields=["article", "position"], name="article_passage_order_idx"),
        ),
    ]
