# Generated by Django 6.0.2 on 2026-03-06 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimanswer_claimvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', '-created_at'], name='claim_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-created_at'], name='claim_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('created_by', 'normalized_query'), name='unique_claim_per_user_normalized_query'),
        ),
    ]
