# Generated by Django 6.0.2 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_claim_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='confidence_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='verdict',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False'), ('uncertain', 'Uncertain')], max_length=20, null=True),
        ),
    ]
