# Generated by Codex on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0005_claim_confidence_percent_claim_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="evidence_snapshot_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="verification_corpus_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="verified_sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
